version: '3'

services:
  backend:
    depends_on:
      - mongodb
    build: ./backend
    container_name: car_shop_back
    ports:
      - 3001:3001
    restart: always
    tty: true
    stdin_open: true
    command: bash
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CarShop

  mongodb:
    image: mongo:5.0.7
    container_name: car_shop_db
    ports:
      - 27017:27017
    restart: always
    volumes:
      - vidly:/data/db

  frontend:
    depends_on:
      - backend
    build: ./frontend
    container_name: car_shop_front
    ports:
      - 3000:3000
    restart: always
    tty: true
    stdin_open: true
    command: bash
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001

networks:
  default:
    external:
      name: car_shop_net

volumes:
  vidly:
